#!/bin/sh
mvn clean package && docker build -t jinallad/MSAclient2 .
docker rm -f MSAclient2 2>/dev/null || true && docker run -it --name MSAclient2 -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSAclient2 jinallad/MSAclient2
