#!/bin/sh
mvn clean package && docker build -t jinallad/practice .
docker rm -f practice 2>/dev/null || true && docker run -it --name practice -p 8080:8080 -p 4848:4848 -p 8181:8181 --name practice jinallad/practice
